
// This file has been generated by the GUI designer. Do not modify.
public partial class ConvertToTransferWindow
{
	private global::Gtk.Table table1;
	private global::Gtk.Button button1;
	private global::Gtk.Label label1;
	private global::Gtk.Label label2;
	private global::Gtk.Entry maxDays;
	private global::Gtk.Entry maxExchangeRate;
	private global::Gtk.Entry minDays;
	private global::Gtk.Entry minExchangeRate;
	private global::Gtk.Button saveButton;
	private global::Gtk.ScrolledWindow scrolledwindow1;
	private global::Gtk.Table resultsTable;
	private global::Gtk.Label label3;
	private global::Gtk.Label label4;
	private global::Gtk.Label label5;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget ConvertToTransferWindow
		this.Name = "ConvertToTransferWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.DefaultWidth = 800;
		// Container child ConvertToTransferWindow.Gtk.Container+ContainerChild
		this.table1 = new global::Gtk.Table (((uint)(5)), ((uint)(4)), false);
		this.table1.Name = "table1";
		this.table1.RowSpacing = ((uint)(6));
		this.table1.ColumnSpacing = ((uint)(6));
		// Container child table1.Gtk.Table+TableChild
		this.button1 = new global::Gtk.Button ();
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.Label = global::Mono.Unix.Catalog.GetString ("Search");
		this.table1.Add (this.button1);
		global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table1 [this.button1]));
		w1.TopAttach = ((uint)(2));
		w1.BottomAttach = ((uint)(3));
		w1.LeftAttach = ((uint)(1));
		w1.RightAttach = ((uint)(3));
		w1.XOptions = ((global::Gtk.AttachOptions)(4));
		w1.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Min/Maximum days between payment and receipt:");
		this.table1.Add (this.label1);
		global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1 [this.label1]));
		w2.XOptions = ((global::Gtk.AttachOptions)(4));
		w2.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Min/Max exchange rate:");
		this.table1.Add (this.label2);
		global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1 [this.label2]));
		w3.TopAttach = ((uint)(1));
		w3.BottomAttach = ((uint)(2));
		w3.XOptions = ((global::Gtk.AttachOptions)(4));
		w3.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.maxDays = new global::Gtk.Entry ();
		this.maxDays.WidthRequest = 60;
		this.maxDays.CanFocus = true;
		this.maxDays.Name = "maxDays";
		this.maxDays.Text = global::Mono.Unix.Catalog.GetString ("5");
		this.maxDays.IsEditable = true;
		this.maxDays.InvisibleChar = '●';
		this.table1.Add (this.maxDays);
		global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1 [this.maxDays]));
		w4.LeftAttach = ((uint)(2));
		w4.RightAttach = ((uint)(3));
		w4.XOptions = ((global::Gtk.AttachOptions)(0));
		w4.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.maxExchangeRate = new global::Gtk.Entry ();
		this.maxExchangeRate.WidthRequest = 60;
		this.maxExchangeRate.CanFocus = true;
		this.maxExchangeRate.Name = "maxExchangeRate";
		this.maxExchangeRate.Text = global::Mono.Unix.Catalog.GetString ("1");
		this.maxExchangeRate.IsEditable = true;
		this.maxExchangeRate.InvisibleChar = '●';
		this.table1.Add (this.maxExchangeRate);
		global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1 [this.maxExchangeRate]));
		w5.TopAttach = ((uint)(1));
		w5.BottomAttach = ((uint)(2));
		w5.LeftAttach = ((uint)(2));
		w5.RightAttach = ((uint)(3));
		w5.XOptions = ((global::Gtk.AttachOptions)(0));
		w5.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.minDays = new global::Gtk.Entry ();
		this.minDays.WidthRequest = 60;
		this.minDays.CanFocus = true;
		this.minDays.Name = "minDays";
		this.minDays.Text = global::Mono.Unix.Catalog.GetString ("0");
		this.minDays.IsEditable = true;
		this.minDays.InvisibleChar = '●';
		this.table1.Add (this.minDays);
		global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1 [this.minDays]));
		w6.LeftAttach = ((uint)(1));
		w6.RightAttach = ((uint)(2));
		w6.XOptions = ((global::Gtk.AttachOptions)(0));
		w6.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.minExchangeRate = new global::Gtk.Entry ();
		this.minExchangeRate.WidthRequest = 60;
		this.minExchangeRate.CanFocus = true;
		this.minExchangeRate.Name = "minExchangeRate";
		this.minExchangeRate.Text = global::Mono.Unix.Catalog.GetString ("1");
		this.minExchangeRate.IsEditable = true;
		this.minExchangeRate.WidthChars = 0;
		this.minExchangeRate.InvisibleChar = '●';
		this.table1.Add (this.minExchangeRate);
		global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1 [this.minExchangeRate]));
		w7.TopAttach = ((uint)(1));
		w7.BottomAttach = ((uint)(2));
		w7.LeftAttach = ((uint)(1));
		w7.RightAttach = ((uint)(2));
		w7.XOptions = ((global::Gtk.AttachOptions)(0));
		w7.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.saveButton = new global::Gtk.Button ();
		this.saveButton.CanFocus = true;
		this.saveButton.Name = "saveButton";
		this.saveButton.UseUnderline = true;
		this.saveButton.Label = global::Mono.Unix.Catalog.GetString ("Save");
		this.table1.Add (this.saveButton);
		global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table1 [this.saveButton]));
		w8.TopAttach = ((uint)(4));
		w8.BottomAttach = ((uint)(5));
		w8.LeftAttach = ((uint)(3));
		w8.RightAttach = ((uint)(4));
		w8.XOptions = ((global::Gtk.AttachOptions)(4));
		w8.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.scrolledwindow1 = new global::Gtk.ScrolledWindow ();
		this.scrolledwindow1.CanFocus = true;
		this.scrolledwindow1.Name = "scrolledwindow1";
		this.scrolledwindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child scrolledwindow1.Gtk.Container+ContainerChild
		global::Gtk.Viewport w9 = new global::Gtk.Viewport ();
		w9.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child GtkViewport.Gtk.Container+ContainerChild
		this.resultsTable = new global::Gtk.Table (((uint)(3)), ((uint)(3)), false);
		this.resultsTable.Name = "resultsTable";
		this.resultsTable.RowSpacing = ((uint)(6));
		this.resultsTable.ColumnSpacing = ((uint)(6));
		// Container child resultsTable.Gtk.Table+TableChild
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("From");
		this.resultsTable.Add (this.label3);
		global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.resultsTable [this.label3]));
		w10.XOptions = ((global::Gtk.AttachOptions)(4));
		w10.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child resultsTable.Gtk.Table+TableChild
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("OK");
		this.resultsTable.Add (this.label4);
		global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.resultsTable [this.label4]));
		w11.LeftAttach = ((uint)(1));
		w11.RightAttach = ((uint)(2));
		w11.XOptions = ((global::Gtk.AttachOptions)(4));
		w11.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child resultsTable.Gtk.Table+TableChild
		this.label5 = new global::Gtk.Label ();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("To");
		this.resultsTable.Add (this.label5);
		global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.resultsTable [this.label5]));
		w12.LeftAttach = ((uint)(2));
		w12.RightAttach = ((uint)(3));
		w12.XOptions = ((global::Gtk.AttachOptions)(4));
		w12.YOptions = ((global::Gtk.AttachOptions)(4));
		w9.Add (this.resultsTable);
		this.scrolledwindow1.Add (w9);
		this.table1.Add (this.scrolledwindow1);
		global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table1 [this.scrolledwindow1]));
		w15.TopAttach = ((uint)(3));
		w15.BottomAttach = ((uint)(4));
		w15.RightAttach = ((uint)(4));
		this.Add (this.table1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultHeight = 305;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.saveButton.Clicked += new global::System.EventHandler (this.OnSaveButtonClicked);
		this.button1.Clicked += new global::System.EventHandler (this.OnSearch);
	}
}
